### ISSUE TITLE
Please specify unit of length

### ISSUE THREAD

**Issue by kseistrup** [wdm0006/pygeohash#2]
The `__doc__` string for the `geohash_*_distance()` methods doesn't mention the unit. It would be prudent to include 'm' or 'meter' in the description.

**Comment by wdm0006** [comment]
Good suggestion.  In addition, the documentation in general is lacking, that is a target for the next larger release and would be a great way for someone who wanted to contribute to get started.

**Comment by kseistrup** [comment]
I should have submitted some pull requests, but I weren't able to do so when I reported the issue.

**Comment by wdm0006** [comment]
No worries, happy to get some suggestions.  If you would like to contribute in the future, there is a lot of low hanging fruit in the new stats module, like standard deviation and variance.
