### ISSUE TITLE
haversine → decode_exactly()?

### ISSUE THREAD

**Issue by kseistrup** [wdm0006/pygeohash#3]
Shouldn't the `geohash_haversine_distance()` method use `decode_exactly()`, rather than `decode()`?

**Comment by wdm0006** [comment]
No, decode calls decode_exactly internally, so the same math is being done.  The difference is that decode exactly returns a string that include insignificant figures and leading/trailing zeros, while decode returns a representative float.  In general, for practical use, decode is what you should use.
