### ISSUE TITLE
Can _PRECISION be altered?

### ISSUE THREAD

**Issue by mbrio** [wdm0006/pygeohash#6]
I was looking over the code, and was considering using some of this for a project that I am working on, but would like to alter the values of _PRECISION on my own branch (or even make them configurable). Does the encoding of the hashes rely on these exact values?

**Comment by wdm0006** [comment]
encoding itself doesnt depend on that mapping, but the mapping is based on the encoding logic. I'm not sure of how to practically change the mapping and have things remain correct.
